/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "add.h"

double *
add_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static double  result;

	printf("add(%f,%f) is called \n", argp->a, argp->b);
	result = argp->a + argp->b;

	return &result;
}
