/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "div.h"


void
div_prog_1(char *host,double x, double y)
{
	CLIENT *clnt;
	double  *result_1;
	numbers  divide_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, DIV_PROG, DIV_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	divide_1_arg.a=x;
	divide_1_arg.b=y;
	result_1 = divide_1(&divide_1_arg, clnt);
	if (result_1 == (double *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 4) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	div_prog_1 (host,atoi(argv[2]), atoi(argv[3]));
exit (0);
}
